IC.Baily2<-function(datos,level=0.95){
 N<-sum(datos)
 k<-length(datos)
 pi.p<-(datos+3/8)/(N+1/8)
 alfa<-1-level
 Chi<-qchisq(alfa/k,1,lower.tail=F)
 C1<-Chi/(4*N)
 temp<-sqrt(C1*(C1+1-pi.p))
 LI<-(sqrt(pi.p)-temp)^2/(C1+1)^2
 LS<-(sqrt(pi.p)+temp)^2/(C1+1)^2
 LI<-ifelse(LI<0,0,LI)
 LS<-ifelse(LS>1,1,LS)
 Volumen<-prod(LS-LI)
 list(LI=LI,LS=LS,Volumen=Volumen)
}
